In [1]:
# Criando a conexão
import sqlite3
con = sqlite3.connect("BaseDados.db")

In [2]:
# Criando um cursos
cur = con.cursor()

In [3]:
# Buscando todas as informações da tabela
cur.execute('SELECT * FROM dados')

resultado = cur.fetchall()

In [4]:
import pandas as pd

resultado = pd.DataFrame(resultado)

resultado.columns =  [
    i[0] for i in cur.description
]

resultado.head()

,index,id_aluno,nome_aluno,cod_matricula,e-mail,acesso_plataforma,acesso_liberado,dias_ultimo_acesso,nr_prova,prova_feita,nota_prova
0,0,1,Maria Eduarda da Rocha,38273,maria@hashtag.com,0,1,12,1,1,9.0
1,1,2,Bárbara da Cunha,63546,barbara@hashtag.com,0,1,2,1,1,10.0
2,2,3,Kevin Melo,80515,kevin@hashtag.com,1,1,3,1,1,7.0
3,3,4,Pedro Henrique da Costa,68004,pedro@hashtag.com,1,1,1,1,1,4.0
4,4,5,Mirella Viana,28421,mirella@hashtag.com,1,1,1,1,1,7.0

In [5]:
# Função para consultar dados

def executa_sql(comando):
    cur.execute(comando)
    resultado = cur.fetchall()
    resultado = pd.DataFrame(resultado)
    resultado.columns = [i[0] for i in cur.description]
    print(resultado.shape)
    #display(resultado.head())

    return resultado

In [8]:
executa_sql('SELECT * FROM dados WHERE acesso_plataforma = 0')

(18, 11)

,index,id_aluno,nome_aluno,cod_matricula,e-mail,acesso_plataforma,acesso_liberado,dias_ultimo_acesso,nr_prova,prova_feita,nota_prova
0,0,1,Maria Eduarda da Rocha,38273,maria@hashtag.com,0,1,12,1,1,9.0
1,1,2,Bárbara da Cunha,63546,barbara@hashtag.com,0,1,2,1,1,10.0
2,5,6,Lívia Jesus,22284,lívia@hashtag.com,0,1,14,1,1,8.0
3,9,10,Cauã Porto,42674,cauã@hashtag.com,0,1,2,1,0,NaN
4,10,11,Maria Ferreira,86563,maria@hashtag.com,0,1,1,1,1,7.0
5,12,13,Antônio Azevedo,29022,lovedogs@hashtag.com,0,1,14,1,1,6.0
6,16,17,Francisco Pires,59518,x!c0@hashtag.com,0,1,13,1,0,NaN
7,17,18,Bárbara Freitas,19442,barbara@hashtag.com,0,1,12,1,1,6.0
8,20,1,Maria Eduarda da Rocha,38273,maria@hashtag.com,0,1,12,2,1,8.0
9,21,2,Bárbara da Cunha,63546,barbara@hashtag.com,0,1,2,2,0,NaN
10,24,6,Lívia Jesus,22284,lívia@hashtag.com,0,1,14,2,0,NaN
11,26,11,Maria Ferreira,86563,maria@hashtag.com,0,1,1,2,1,6.0
12,28,13,Antônio Azevedo,29022,lovedogs@hashtag.com,0,1,14,2,0,NaN
13,32,18,Bárbara Freitas,19442,barbara@hashtag.com,0,1,12,2,1,10.0
14,34,1,Maria Eduarda da Rocha,38273,maria@hashtag.com,0,1,12,3,1,6.0
15,35,11,Maria Ferreira,86563,maria@hashtag.com,0,1,1,3,0,NaN
16,38,18,Bárbara Freitas,19442,barbara@hashtag.com,0,1,12,3,0,NaN
17,40,1,Maria Eduarda da Rocha,38273,maria@hashtag.com,0,1,12,4,0,NaN

In [13]:
executa_sql('SELECT DISTINCT nome_aluno, cod_matricula, [e-mail] as email FROM dados \
             WHERE acesso_plataforma = 0 AND dias_ultimo_acesso <= 2')

(3, 3)

         nome_aluno  cod_matricula                email
0  Bárbara da Cunha          63546  barbara@hashtag.com
1        Cauã Porto          42674     cauã@hashtag.com
2    Maria Ferreira          86563    maria@hashtag.com

In [17]:
executa_sql('SELECT DISTINCT nome_aluno, cod_matricula, [e-mail] as email, \
            acesso_plataforma, dias_ultimo_acesso FROM dados \
             WHERE acesso_plataforma = 0 OR dias_ultimo_acesso > 10 ')

(8, 5)

,nome_aluno,cod_matricula,email,acesso_plataforma,dias_ultimo_acesso
0,Maria Eduarda da Rocha,38273,maria@hashtag.com,0,12
1,Bárbara da Cunha,63546,barbara@hashtag.com,0,2
2,Lívia Jesus,22284,lívia@hashtag.com,0,14
3,Cauã Porto,42674,cauã@hashtag.com,0,2
4,Maria Ferreira,86563,maria@hashtag.com,0,1
5,Antônio Azevedo,29022,lovedogs@hashtag.com,0,14
6,Francisco Pires,59518,x!c0@hashtag.com,0,13
7,Bárbara Freitas,19442,barbara@hashtag.com,0,12